-- Generated by DataHub Steward Squad.
-- These SQL checks are examples for reviewers; adapt warehouse syntax before production use.

-- PII null-rate guardrail for finance.fct_revenue.customer_email
select count(*) as row_count,
       sum(case when customer_email is null then 1 else 0 end) as null_count
from finance.fct_revenue;

-- Freshness guardrail for finance.fct_revenue
select max(_loaded_at) as latest_loaded_at
from finance.fct_revenue
having max(_loaded_at) >= current_timestamp - interval '24 hours';
